id: PB046D121
initial_creation_type: input
source_metadata:
  title: Amdo Geshe Jampal Rolwé Lodrö
  language: en
  description: Texts by and about Amdo Geshe Jampal Rolwé Lodrö (a mdo dge bshes 'jam
    dpal rol ba'i blo gros, 1888–1936), a prominent Gelugpa author who composed a
    treatise on Dzogchen and appealed against sectarianism.
  volume:
    75877ac44ebe4902adda45fbfe382fff:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      parent: Aspiration Prayers
created_at: '2022-02-28T22:39:06.514667'
last_modified_at: '2022-02-28T22:39:06.514673'
